name: Sync labels

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository'
        required: true
        type: choice
        options:
          # System
          - EpicMorg/.github
          # Projects
          - EpicMorg/atlassian-downloader
          - EpicMorg/atlassian-json
          - EpicMorg/chocolatey
          - EpicMorg/docker
          - EpicMorg/SourceSDK.ENV.Editor
          - EpicMorg/UniversalValveToolbox
jobs:
  sync:
    name: Sync ${{ inputs.repo }} labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: micnncim/action-label-syncer@v1
        with:
          manifest: .github/labels.yml
          repository: |
            ${{ inputs.repo }}

          token: ${{ secrets.EPICMORG_LABELS_PAT }}
