name: Automatic sync with read-only mirrors

on:
#  push:
#    branches:
#      - main
  schedule:
    - cron: '42 0 * * 0'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        repo:
#         - {github: "", bitbucket: "", codeberg: "", gitlab: "" }
          - {github: "https://github.com/EpicMorg/.github.git", bitbucket: "git@bitbucket.org:epicmorg/.github.git", codeberg: "git@codeberg.org:EpicMorg/.github.git", gitlab: "git@gitlab.com:EpicMorg/dot-github.git"}
          - {github: "https://github.com/EpicMorg/AMXx-Easy-Noclip.git", bitbucket: "git@bitbucket.org:epicmorg/amxx-easy-noclip.git", codeberg: "git@codeberg.org:EpicMorg/AMXx-Easy-Noclip.git", gitlab: "git@gitlab.com:epicmorg/AMXx-Easy-Noclip.git" }
          - {github: "https://github.com/EpicMorg/AMXx-Media-Player.git", bitbucket: "git@bitbucket.org:epicmorg/amxx-media-player.git", codeberg: "git@codeberg.org:EpicMorg/AMXx-Media-Player.git", gitlab: "git@gitlab.com:epicmorg/AMXx-Media-Player.git" }
          - {github: "https://github.com/EpicMorg/AMXx-Model-Spawner-Menu.git", bitbucket: "git@bitbucket.org:epicmorg/amxx-model-spawner-menu.git", codeberg: "git@codeberg.org:EpicMorg/AMXx-Model-Spawner-Menu.git", gitlab: "git@gitlab.com:epicmorg/AMXx-Model-Spawner-Menu.git" }
          - {github: "https://github.com/EpicMorg/AMXx-Player-Renamer.git", bitbucket: "git@bitbucket.org:epicmorg/amxx-player-renamer.git", codeberg: "git@codeberg.org:EpicMorg/AMXx-Player-Renamer.git", gitlab: "git@gitlab.com:epicmorg/AMXx-Player-Renamer.git" }
          - {github: "https://github.com/EpicMorg/AMXx-Sound-connect-announce.git", bitbucket: "git@bitbucket.org:epicmorg/amxx-sound-connect-announce.git", codeberg: "git@codeberg.org:EpicMorg/AMXx-Sound-connect-announce.git", gitlab: "git@gitlab.com:epicmorg/AMXx-Sound-connect-announce.git" }
          - {github: "https://github.com/EpicMorg/atlassian-downloader.git", bitbucket: "git@bitbucket.org:epicmorg/atlassian-downloader.git", codeberg: "git@codeberg.org:EpicMorg/atlassian-downloader.git", gitlab: "git@gitlab.com:EpicMorg/atlassian-downloader.git"}
          - {github: "https://github.com/EpicMorg/atlassian-json.git", bitbucket: "git@bitbucket.org:epicmorg/atlassian-json.git", codeberg: "git@codeberg.org:EpicMorg/atlassian-json.git", gitlab: "git@gitlab.com:EpicMorg/atlassian-json.git"}
          - {github: "https://github.com/EpicMorg/avchd2mp4remuxer.git", bitbucket: "git@bitbucket.org:epicmorg/avchd2mp4remuxer.git", codeberg: "git@codeberg.org:EpicMorg/avchd2mp4remuxer.git", gitlab: "git@gitlab.com:epicmorg/avchd2mp4remuxer.git" }
          - {github: "https://github.com/EpicMorg/binaryBeer.git", bitbucket: "git@bitbucket.org:epicmorg/binarybeer.git", codeberg: "git@codeberg.org:EpicMorg/binaryBeer.git", gitlab: "git@gitlab.com:epicmorg/binaryBeer.git" }
          - {github: "https://github.com/EpicMorg/buildah-wrapper.git", bitbucket: "git@bitbucket.org:epicmorg/buildah-wrapper.git", codeberg: "git@codeberg.org:EpicMorg/buildah-wrapper.git", gitlab: "git@gitlab.com:epicmorg/buildah-wrapper.git" }
          - {github: "https://github.com/EpicMorg/Cachet.git", bitbucket: "git@bitbucket.org:epicmorg/cachet.git", codeberg: "git@codeberg.org:EpicMorg/Cachet.git", gitlab: "git@gitlab.com:epicmorg/Cachet.git" }
          - {github: "https://github.com/EpicMorg/chocolatey.git", bitbucket: "git@bitbucket.org:epicmorg/chocolatey.git", codeberg: "git@codeberg.org:EpicMorg/chocolatey.git", gitlab: "git@gitlab.com:epicmorg/chocolatey.git" }
          - {github: "https://github.com/EpicMorg/CloudFlare-WebPanel.git", bitbucket: "git@bitbucket.org:epicmorg/cloudflare-webpanel.git", codeberg: "git@codeberg.org:EpicMorg/CloudFlare-WebPanel.git", gitlab: "git@gitlab.com:epicmorg/CloudFlare-WebPanel.git" }
          - {github: "https://github.com/EpicMorg/codename_The_Dir.git", bitbucket: "git@bitbucket.org:epicmorg/codename_the_dir.git", codeberg: "git@codeberg.org:EpicMorg/codename_The_Dir.git", gitlab: "git@gitlab.com:epicmorg/codename_The_Dir.git" }
          - {github: "https://github.com/EpicMorg/docker.git", bitbucket: "git@bitbucket.org:epicmorg/docker.git", codeberg: "git@codeberg.org:EpicMorg/docker.git",  gitlab: "git@gitlab.com:EpicMorg/docker.git" }
          - {github: "https://github.com/EpicMorg/Easy-ADB-Screenshoter.git", bitbucket: "git@bitbucket.org:epicmorg/easy-adb-screenshoter.git", codeberg: "git@codeberg.org:EpicMorg/Easy-ADB-Screenshoter.git", gitlab: "git@gitlab.com:epicmorg/Easy-ADB-Screenshoter.git" }
          - {github: "https://github.com/EpicMorg/EasyLame.git", bitbucket: "git@bitbucket.org:epicmorg/easylame.git", codeberg: "git@codeberg.org:EpicMorg/EasyLame.git", gitlab: "git@gitlab.com:epicmorg/EasyLame.git" }
          - {github: "https://github.com/EpicMorg/EMArcadeShell.git", bitbucket: "git@bitbucket.org:epicmorg/emarcadeshell.git", codeberg: "git@codeberg.org:EpicMorg/EMArcadeShell.git", gitlab: "git@gitlab.com:epicmorg/EMArcadeShell.git" }
          - {github: "https://github.com/EpicMorg/EMFILEMOVER.git", bitbucket: "git@bitbucket.org:epicmorg/emfilemover.git", codeberg: "git@codeberg.org:EpicMorg/EMFILEMOVER.git", gitlab: "git@gitlab.com:epicmorg/EMFILEMOVER.git" }
          - {github: "https://github.com/EpicMorg/EMHP.git", bitbucket: "git@bitbucket.org:epicmorg/emhp.git", codeberg: "git@codeberg.org:EpicMorg/EMHP.git", gitlab: "git@gitlab.com:epicmorg/EMHP.git" }
          - {github: "https://github.com/EpicMorg/EMRadio.git", bitbucket: "git@bitbucket.org:epicmorg/emradio.git", codeberg: "git@codeberg.org:EpicMorg/EMRadio.git", gitlab: "git@gitlab.com:epicmorg/EMRadio.git" }
          - {github: "https://github.com/EpicMorg/EMREX.git", bitbucket: "git@bitbucket.org:epicmorg/emrex.git", codeberg: "git@codeberg.org:EpicMorg/EMREX.git", gitlab: "git@gitlab.com:epicmorg/EMREX.git" }
          - {github: "https://github.com/EpicMorg/EMRJT.git", bitbucket: "git@bitbucket.org:epicmorg/emrjt.git", codeberg: "git@codeberg.org:EpicMorg/EMRJT.git", gitlab: "git@gitlab.com:epicmorg/EMRJT.git" }
          - {github: "https://github.com/EpicMorg/emscripts.git", bitbucket: "git@bitbucket.org:epicmorg/emscripts.git", codeberg: "git@codeberg.org:EpicMorg/emscripts.git", gitlab: "git@gitlab.com:epicmorg/emscripts.git" }
          - {github: "https://github.com/EpicMorg/EMST.git", bitbucket: "git@bitbucket.org:epicmorg/emst.git", codeberg: "git@codeberg.org:EpicMorg/EMST.git", gitlab: "git@gitlab.com:epicmorg/EMST.git" }
          - {github: "https://github.com/EpicMorg/EMTG.git", bitbucket: "git@bitbucket.org:epicmorg/emtg.git", codeberg: "git@codeberg.org:EpicMorg/EMTG.git", gitlab: "git@gitlab.com:epicmorg/EMTG.git" }
          - {github: "https://github.com/EpicMorg/EpicMorg-Supervisor.git", bitbucket: "git@bitbucket.org:epicmorg/epicmorg-supervisor.git", codeberg: "git@codeberg.org:EpicMorg/EpicMorg-Supervisor.git", gitlab: "git@gitlab.com:epicmorg/EpicMorg-Supervisor.git" }
#          - {github: "", bitbucket: "", codeberg: "", gitlab: "" }
#          - {github: "", bitbucket: "", codeberg: "", gitlab: "" }
#          - {github: "", bitbucket: "", codeberg: "", gitlab: "" }
#          - {github: "", bitbucket: "", codeberg: "", gitlab: "" }
#          - {github: "", bitbucket: "", codeberg: "", gitlab: "" }
#          - {github: "", bitbucket: "", codeberg: "", gitlab: "" }
#          - {github: "", bitbucket: "", codeberg: "", gitlab: "" }
#          - {github: "", bitbucket: "", codeberg: "", gitlab: "" }
#          - {github: "", bitbucket: "", codeberg: "", gitlab: "" }
#          - {github: "", bitbucket: "", codeberg: "", gitlab: "" }
#          - {github: "", bitbucket: "", codeberg: "", gitlab: "" }
#          - {github: "", bitbucket: "", codeberg: "", gitlab: "" }
#          - {github: "", bitbucket: "", codeberg: "", gitlab: "" }
#          - {github: "", bitbucket: "", codeberg: "", gitlab: "" }
#          - {github: "", bitbucket: "", codeberg: "", gitlab: "" }

    steps:
      - name: Set up SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -t rsa,ed25519 bitbucket.org >> ~/.ssh/known_hosts
          ssh-keyscan -t rsa,ed25519 codeberg.org >> ~/.ssh/known_hosts
          ssh-keyscan -t rsa,ed25519 github.com >> ~/.ssh/known_hosts
          ssh-keyscan -t rsa,ed25519 gitlab.com >> ~/.ssh/known_hosts

      - name: Clone repository as mirror
        run: |
          git clone --mirror ${{ matrix.repo.github }} repo-mirror

      - name: Push to BitBucket
        run: |
          cd repo-mirror
          git remote set-url origin ${{ matrix.repo.bitbucket }}
          git push --mirror --force

      - name: Push to CodeBerg
        run: |
          cd repo-mirror
          git remote set-url origin ${{ matrix.repo.codeberg }}
          git push --mirror --force

      - name: Push to GitLab
        run: |
          cd repo-mirror
          git remote set-url origin ${{ matrix.repo.gitlab }}
          git push --mirror --force
